- name: install nginx on ec2s
  hosts: nginx_proxy
  become: yes
  vars_files:
  - secrets.yml  
  vars:
  tasks: # List of tasks to execute
    # - name: "no comment"
    #   shell: "touch aliii"
  - name: Update package list # Task name
    dnf: # Module to use for the task
      update_cache: yes # Update the package cache
  - name: install nginx
    dnf:
      name: nginx
      state: present
  - name: configure nginx
    blockinfile:
      path: /etc/nginx/conf.d/proxy.conf
      block: server { listen 80; location / { proxy_pass http://{{ nlb_dns }}; }}
  - name: start and enable nginx
    systemd:
      name: nginx
      state: started
      enabled: true

      #   "sudo yum install -y nginx",
  #   "sudo systemctl start nginx",
  #   "sudo systemctl enable nginx",
  #   "echo 'server { listen 80; location / { proxy_pass http://${module.nlb-private.nlb-dns}; }}' | sudo tee /etc/nginx/conf.d/proxy.conf",
  #   "sudo systemctl restart nginx"