- name: install nginx on ec2s
  hosts: nginx_proxy
  
  tasks: 
  - name: install nginx
    yum:
      name: nginx
      state: present
  - name: configure nginx
    blockinfile:
      path: /etc/nginx/conf.d/proxy.conf
      block: server { listen 80; location / { proxy_pass http://{{ nlb-dns }}; }}
  - name: start and enable nginx
    yum:
      name: nginx
      state: started
      enabled: true

      #   "sudo yum install -y nginx",
  #   "sudo systemctl start nginx",
  #   "sudo systemctl enable nginx",
  #   "echo 'server { listen 80; location / { proxy_pass http://${module.nlb-private.nlb-dns}; }}' | sudo tee /etc/nginx/conf.d/proxy.conf",
  #   "sudo systemctl restart nginx"