- name: install nginx on ec2s
  hosts: nginx_proxy
  become: yes  
  vars:
  tasks: 
  - name: install nginx
    yum:
      name: nginx
      state: present
      update_cache: yes # Update the package cache
  - name: Enable service httpd, and not touch the state
    service:
        name: nginx
        enabled: yes    
  - name:
    file:
      path: /etc/nginx/conf.d/proxy.conf
      state: touch
  - name: configure nginx
    blockinfile:
      path: /etc/nginx/conf.d/proxy.conf
      block: server { listen 80; location / { proxy_pass http://{{ nlb_dns }}; }}
  - name: start and enable nginx
    become: yes
    service:
      name: nginx
      state: restarted
      enabled: yes
      daemon_reload: yes

      #   "sudo yum install -y nginx",
  #   "sudo systemctl start nginx",
  #   "sudo systemctl enable nginx",
  #   "echo 'server { listen 80; location / { proxy_pass http://${module.nlb-private.nlb-dns}; }}' | sudo tee /etc/nginx/conf.d/proxy.conf",
  #   "sudo systemctl restart nginx"